Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option("display.max_columns", None)

Load dataset

In [4]:
df = pd.read_csv("../dataset/airline_operations.csv")

In [5]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2020,12,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",44.0,3.0,1.63,0.0,0.12,0.0,1.25,0.0,1.0,89.0,56.0,0.0,3.0,0.0,30.0
1,2020,12,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",90.0,1.0,0.96,0.0,0.04,0.0,0.00,0.0,0.0,23.0,22.0,0.0,1.0,0.0,0.0
2,2020,12,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",88.0,8.0,5.75,0.0,1.60,0.0,0.65,0.0,1.0,338.0,265.0,0.0,45.0,0.0,28.0
3,2020,12,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",184.0,9.0,4.17,0.0,1.83,0.0,3.00,0.0,0.0,508.0,192.0,0.0,92.0,0.0,224.0
4,2020,12,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",76.0,11.0,4.78,0.0,5.22,0.0,1.00,1.0,0.0,692.0,398.0,0.0,178.0,0.0,116.0

In [7]:
df.shape

(3351, 21)

In [8]:
df.columns

Index(['year', 'month', 'carrier', 'carrier_name', 'airport', 'airport_name',
       'arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct',
       'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted',
       'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay',
       'security_delay', 'late_aircraft_delay'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3351 entries, 0 to 3350
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 3351 non-null   int64
 1   month                3351 non-null   int64
 2   carrier              3351 non-null   object
 3   carrier_name         3351 non-null   object
 4   airport              3351 non-null   object
 5   airport_name         3351 non-null   object
 6   arr_flights          3343 non-null   float64
 7   arr_del15            3343 non-null   float64
 8   carrier_ct           3343 non-null   float64
 9   weather_ct           3343 non-null   float64
 10  nas_ct               3343 non-null   float64
 11  security_ct          3343 non-null   float64
 12  late_aircraft_ct     3343 non-null   float64
 13  arr_cancelled        3343 non-null   float64
 14  arr_diverted         3343 non-null   float64
 15  arr_delay            3343 non-null   float64
 16  carrier_delay        3343 non-null   float64
 17  weather_delay        3343 non-null   float64
 18  nas_delay            3343 non-null   float64
 19  security_delay       3343 non-null   float64
 20  late_aircraft_delay  3343 non-null   float64
dtypes: float64(15), int64(2), object(4)
memory usage: 549.9+ KB

In [10]:
df.describe()

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
count,3351.000000,3351.0,3343.000000,3343.000000,3343.000000,3343.000000,3343.000000,3343.000000,3343.000000,3343.000000,3343.000000,3343.000000,3343.000000,3343.000000,3343.00000,3343.000000,3343.000000
mean,2019.459266,12.0,298.271014,50.995214,16.065337,1.443144,16.183383,0.137320,17.166069,2.884535,0.575830,3333.868083,1144.763087,177.591385,749.57942,5.400838,1256.533353
std,0.498412,0.0,852.436335,146.484456,41.759516,4.821657,56.423008,0.646479,55.447043,10.126658,2.097884,10284.926623,3371.103512,734.343542,3190.50916,27.161402,4184.451426
min,2019.000000,12.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,2019.000000,12.0,35.000000,5.000000,1.490000,0.000000,0.820000,0.000000,0.900000,0.000000,0.000000,230.000000,68.500000,0.000000,21.50000,0.000000,31.000000
50%,2019.000000,12.0,83.000000,12.000000,4.750000,0.060000,2.980000,0.000000,3.280000,0.000000,0.000000,746.000000,272.000000,3.000000,106.00000,0.000000,205.000000
75%,2020.000000,12.0,194.500000,33.000000,12.255000,1.010000,8.870000,0.000000,10.240000,2.000000,0.000000,2095.500000,830.500000,82.000000,362.00000,0.000000,724.000000
max,2020.000000,12.0,19713.000000,2289.000000,697.000000,89.420000,1039.540000,17.310000,819.660000,224.000000,42.000000,160383.000000,55215.000000,14219.000000,82064.00000,553.000000,75179.000000

In [11]:
df.isnull().sum()

year                   0
month                  0
carrier                0
carrier_name           0
airport                0
airport_name           0
arr_flights            8
arr_del15              8
carrier_ct             8
weather_ct             8
nas_ct                 8
security_ct            8
late_aircraft_ct       8
arr_cancelled          8
arr_diverted           8
arr_delay              8
carrier_delay          8
weather_delay          8
nas_delay              8
security_delay         8
late_aircraft_delay    8
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['carrier_name'].unique()

array(['Endeavor Air Inc.', 'American Airlines Inc.',
       'Alaska Airlines Inc.', 'JetBlue Airways', 'Delta Air Lines Inc.',
       'Frontier Airlines Inc.', 'Allegiant Air',
       'Hawaiian Airlines Inc.', 'Envoy Air', 'Spirit Air Lines',
       'PSA Airlines Inc.', 'SkyWest Airlines Inc.', 'Republic Airline',
       'United Air Lines Inc.', 'Southwest Airlines Co.',
       'Mesa Airlines Inc.', 'ExpressJet Airlines LLC'], dtype=object)

In [15]:
df['carrier_name'].nunique()

17

In [16]:
df['airport_name'].nunique()

360

In [17]:
df['year'].value_counts()

year
2019    1812
2020    1539
Name: count, dtype: int64

In [20]:
df=df.dropna()

In [21]:
df.isnull().sum()

year                   0
month                  0
carrier                0
carrier_name           0
airport                0
airport_name           0
arr_flights            0
arr_del15              0
carrier_ct             0
weather_ct             0
nas_ct                 0
security_ct            0
late_aircraft_ct       0
arr_cancelled          0
arr_diverted           0
arr_delay              0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64

In [22]:
df.shape

(3343, 21)

In [23]:
df = df.rename(columns={
    'year':'Year',
    'month':'Month',
    'carrier':'Carrier_Code',
    'carrier_name':'Airline',
    'airport':'Airport_Code',
    'airport_name':'Airport',
    'arr_flights':'Total_Flights',
    'arr_del15':'Delayed_Flights',
    'carrier_ct':'Carrier_Delays',
    'weather_ct':'Weather_Delays',
    'nas_ct':'NAS_Delays',
    'security_ct':'Security_Delays',
    'late_aircraft_ct':'Late_Aircraft_Delays',
    'arr_cancelled':'Cancelled_Flights',
    'arr_diverted':'Diverted_Flights',
    'arr_delay':'Total_Delay_Minutes',
    'carrier_delay':'Carrier_Delay_Minutes',
    'weather_delay':'Weather_Delay_Minutes',
    'nas_delay':'NAS_Delay_Minutes',
    'security_delay':'Security_Delay_Minutes',
    'late_aircraft_delay':'Late_Aircraft_Delay_Minutes'
})

In [24]:
df.columns

Index(['Year', 'Month', 'Carrier_Code', 'Airline', 'Airport_Code', 'Airport',
       'Total_Flights', 'Delayed_Flights', 'Carrier_Delays', 'Weather_Delays',
       'NAS_Delays', 'Security_Delays', 'Late_Aircraft_Delays',
       'Cancelled_Flights', 'Diverted_Flights', 'Total_Delay_Minutes',
       'Carrier_Delay_Minutes', 'Weather_Delay_Minutes', 'NAS_Delay_Minutes',
       'Security_Delay_Minutes', 'Late_Aircraft_Delay_Minutes'],
      dtype='object')

On-Time Flights

In [26]:
df['On_Time_Flights'] = df['Total_Flights'] - df['Delayed_Flights']

Delay Percentage

In [27]:
df['Delay_Percentage'] = (
    df['Delayed_Flights'] / df['Total_Flights']
) * 100

Cancellation Percentage

In [28]:
df['Cancellation_Percentage'] = (
    df['Cancelled_Flights'] / df['Total_Flights']
) * 100

Average Delay per Delayed Flight

In [29]:
df['Average_Delay_Per_Flight'] = (
    df['Total_Delay_Minutes'] /
    df['Delayed_Flights']
)

On-Time Percentage

In [30]:
df['On_Time_Percentage'] = (
    df['On_Time_Flights'] /
    df['Total_Flights']
) * 100

Delay Severity

In [31]:
def delay_level(delay):

    if delay < 15:
        return "Low"

    elif delay < 30:
        return "Moderate"

    elif delay < 60:
        return "High"

    else:
        return "Critical"

df['Delay_Severity'] = df['Average_Delay_Per_Flight'].apply(delay_level)

In [32]:
df.head()

,Year,Month,Carrier_Code,Airline,Airport_Code,Airport,Total_Flights,Delayed_Flights,Carrier_Delays,Weather_Delays,NAS_Delays,Security_Delays,Late_Aircraft_Delays,Cancelled_Flights,Diverted_Flights,Total_Delay_Minutes,Carrier_Delay_Minutes,Weather_Delay_Minutes,NAS_Delay_Minutes,Security_Delay_Minutes,Late_Aircraft_Delay_Minutes,On_Time_Flights,Delay_Percentage,Cancellation_Percentage,Average_Delay_Per_Flight,On_Time_Percentage,Delay_Severity
0,2020,12,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",44.0,3.0,1.63,0.0,0.12,0.0,1.25,0.0,1.0,89.0,56.0,0.0,3.0,0.0,30.0,41.0,6.818182,0.000000,29.666667,93.181818,Moderate
1,2020,12,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",90.0,1.0,0.96,0.0,0.04,0.0,0.00,0.0,0.0,23.0,22.0,0.0,1.0,0.0,0.0,89.0,1.111111,0.000000,23.000000,98.888889,Moderate
2,2020,12,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",88.0,8.0,5.75,0.0,1.60,0.0,0.65,0.0,1.0,338.0,265.0,0.0,45.0,0.0,28.0,80.0,9.090909,0.000000,42.250000,90.909091,High
3,2020,12,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",184.0,9.0,4.17,0.0,1.83,0.0,3.00,0.0,0.0,508.0,192.0,0.0,92.0,0.0,224.0,175.0,4.891304,0.000000,56.444444,95.108696,High
4,2020,12,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",76.0,11.0,4.78,0.0,5.22,0.0,1.00,1.0,0.0,692.0,398.0,0.0,178.0,0.0,116.0,65.0,14.473684,1.315789,62.909091,85.526316,Critical

In [33]:
df.to_csv("../dataset/airline_operations_cleaned.csv", index=False)

In [34]:
df.columns

Index(['Year', 'Month', 'Carrier_Code', 'Airline', 'Airport_Code', 'Airport',
       'Total_Flights', 'Delayed_Flights', 'Carrier_Delays', 'Weather_Delays',
       'NAS_Delays', 'Security_Delays', 'Late_Aircraft_Delays',
       'Cancelled_Flights', 'Diverted_Flights', 'Total_Delay_Minutes',
       'Carrier_Delay_Minutes', 'Weather_Delay_Minutes', 'NAS_Delay_Minutes',
       'Security_Delay_Minutes', 'Late_Aircraft_Delay_Minutes',
       'On_Time_Flights', 'Delay_Percentage', 'Cancellation_Percentage',
       'Average_Delay_Per_Flight', 'On_Time_Percentage', 'Delay_Severity'],
      dtype='object')